# Generated by Django 6.0.4 on 2026-05-01 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('country', models.CharField(choices=[('indonesia', 'Indonesia'), ('malaysia', 'Malaysia'), ('thailand', 'Thailand'), ('other', 'Other')], default='indonesia', max_length=20)),
                ('level', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('short', 'Short Course')], max_length=20)),
                ('university', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('benefits', models.TextField(help_text='One benefit per line')),
                ('requirements', models.TextField(help_text='One requirement per line')),
                ('deadline', models.DateField()),
                ('image', models.ImageField(blank=True, help_text='Scholarship cover image', null=True, upload_to='scholarships/')),
                ('link', models.URLField(blank=True, help_text='Official scholarship page URL')),
                ('whatsapp_contact', models.CharField(blank=True, help_text='WhatsApp number to contact for this scholarship', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='WhatsApp with country code e.g. +22376543210', max_length=30)),
                ('nationality', models.CharField(max_length=100)),
                ('current_education', models.CharField(max_length=200)),
                ('motivation', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not shown to applicant)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarship')),
            ],
        ),
    ]
