# Generated by Django 6.0.4 on 2026-05-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('innovation', 'Innovation'), ('solution', 'Solution Sur Mesure')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('dev', 'En développement'), ('live', 'En ligne'), ('done', 'Mission accomplie')], max_length=10)),
                ('sector', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='One feature per line')),
                ('technologies', models.CharField(blank=True, max_length=300)),
                ('icon_emoji', models.CharField(default='💡', max_length=10)),
                ('icon_color', models.CharField(default='#3b82f6', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('student', 'Student'), ('client', 'Client')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('avatar', models.CharField(default='👤', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
