# Generated by Django 6.0.4 on 2026-05-01 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('career', 'Career Development'), ('tech', 'Technical Skills'), ('leadership', 'Leadership'), ('ai', 'AI & Machine Learning'), ('scholarship', 'Scholarship Guidance')], max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live Now'), ('past', 'Past')], default='upcoming', max_length=10)),
                ('date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=90, help_text='Duration in minutes')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Webinar cover image', null=True, upload_to='webinars/')),
                ('speaker_name', models.CharField(max_length=200)),
                ('speaker_role', models.CharField(max_length=200)),
                ('speaker_company', models.CharField(blank=True, max_length=200)),
                ('speaker_photo', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('zoom_link', models.URLField(blank=True, help_text='Zoom / Google Meet link for registered participants')),
                ('zoom_password', models.CharField(blank=True, help_text='Meeting password if any', max_length=100)),
                ('recording_link', models.URLField(blank=True)),
                ('is_free', models.BooleanField(default=True)),
                ('max_seats', models.PositiveIntegerField(default=100)),
                ('whatsapp_group', models.CharField(blank=True, help_text='WhatsApp group invite link', max_length=300)),
                ('certificate_enabled', models.BooleanField(default=True, help_text='Send e-certificates after webinar ends')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='WhatsApp number with country code e.g. +22376543210', max_length=30)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('certificate_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('certificate_sent', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False, help_text='Mark as attended to send certificate')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='webinars.webinar')),
            ],
            options={
                'unique_together': {('webinar', 'email')},
            },
        ),
    ]
